// Animals
export const SELECT_ANIMAL = 'SELECT_ANIMAL'
export const START_LOADING = 'START_LOADING'
export const END_LOADING = 'END_LOADING'
export const FETCH_ANIMALS_LIST = 'FETCH_ANIMALS_LIST'
export const FETCH_ANIMALS_LIST_FIRST_LOAD = 'FETCH_ANIMALS_LIST_FIRST_LOAD'
export const FETCH_ANIMALS_LIST_BY_BATCH = 'FETCH_ANIMALS_BY_BATCH'